In [9]:
import numpy as np
A=np.array([[12,5,8,20],
            [7,15,3,11],
            [10,14,2,16]])
listmean=np.mean(A,axis=1)
#print(listmean)
#print(A)
i=0
for row in A:
    row[row<listmean[i]]=0
    row[row>=listmean[i]]=1
    i=i+1
print(A)
count=np.count_nonzero(A, axis=1)


print(count)



[[1 0 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[2 2 2]


In [ ]:
import numpy as np
X = np.array([ [10, 100, 5],
               [12, 110, 6],
               [11, 105, 7],
               [13, 500, 6],
               [14, 108, 8],
               [15, 115, 9] ])
listmean=np.mean(X,axis=0)
print(listmean)
liststandarddeviation=np.std(X,axis=0)
Y=np.array([[]])
listmedian=np.median(X,axis=0)
outliner=np.abs(X-listmean)>2*liststandarddeviation
Y=X
print(outliner)
Y[outliner] = np.broadcast_to(listmedian, X.shape)[outliner]
print(Y)

In [2]:
import pandas as pd

df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],
                    'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],
                    'Gender': ['F','M','F','M','M','F','F','M'],
                    'Marks': [85,72,91,65,78,88,95,70],
                    'Attendance': [92,81,96,72,85,90,98,75] })
cseav=df[df[ "Department"]=="CSE"]["Marks"].mean()
eceav=df[df[ "Department"]=="ECE"]["Marks"].mean()
print(df[(df["Department"] == "CSE") & (df["Gender"] == "M")]["Marks"].mean())
print(df[df[ "Department"]=="CSE"]["Marks"].max())
print(df[df[ "Department"]=="ECE"]["Marks"].max())
print(df[df[ "Department"]=="CSE"]["Marks"]>cseav)
print(df[df[ "Department"]=="ECE"]["Marks"]>eceav)
cseaeavatt=df[df["Department"]=="CSE"]["Attendance"].mean()
eseavatt=df[df["Department"]=="ECE"]["Attendance"].mean()
if(cseaeavatt>eseavatt):
    print("cse average attendance have highest : ",cseaeavatt)
else:
    print("ese average attendance have highest: ",eseavatt)



75.0
95
91
0     True
1    False
4    False
6     True
Name: Marks, dtype: bool
2     True
3    False
5     True
7    False
Name: Marks, dtype: bool
cse average attendance have highest :  89.0


In [5]:
import pandas as pd
df = pd.DataFrame({ 'ID': [101,102,103,101,104,102,105],
                    'Name': ['A','B','C','A','D','B','E'],
                    'Age': [20,21,22,20,23,21,24],
                    'Score': [80,75,90,85,88,75,92] })

duplicated_ID=df[df.duplicated('ID',keep=False)]['ID'].unique()
print(" duplicated IDs:",duplicated_ID)
for id_value,group in df.groupby('ID'):
    if(len(group)>1):
        iden=group.drop(columns='ID').nunique().max()==1
        print(f"id :{id_value}:records identical ={iden}")
#4Q) 3
clean_df=df.sort_values('Score',ascending=False)
clean_df=clean_df.drop_duplicates(subset='ID',keep='first')
print(clean_df)
#4Q)4
clean_df=clean_df.sort_values('ID').reset_index(drop=True)
print(clean_df)
#4Q)5
print(len(df)-len(clean_df)," records were removed:")



 duplicated IDs: [101 102]
id :101:records identical =False
id :102:records identical =True
    ID Name  Age  Score
6  105    E   24     92
2  103    C   22     90
4  104    D   23     88
3  101    A   20     85
1  102    B   21     75
    ID Name  Age  Score
0  101    A   20     85
1  102    B   21     75
2  103    C   22     90
3  104    D   23     88
4  105    E   24     92
2  records were removed:


In [ ]:
import pandas as pd
df = pd.DataFrame({ 'Date':
                   [ '2026-01-01',
                    '2026-01-02',
                    '2026-01-04',
                    '2026-01-05',
                    '2026-01-08',
                    '2026-01-09' ],
                    'Sales': [100,120,150,130,180,200] })
#1Q)
df['Date']=pd.to_datetime(df['Date'])
print(df.dtypes)
print(df)
#2Q)
all_dates=pd.date_range(start=df['Date'].min(),end=df['Date'].max(),freq='D')
print(all_dates)
df=df.set_index('Date')
print(df)
df=df.reindex(all_dates)
print(df)
df['Avg']=df['Sales'].rolling(window=3,min_periods=1).mean()

print(df)
max_date=df['Avg'].idxmax()
print("Date on which the rolling average is maximum",max_date)
print("maximum rolling average:",df['Avg'].max())

In [ ]:
import numpy as np
P = np.array([ [1, 2], [4, 6], [7, 3], [2, 8], [9, 5] ])
diff=P[:,np.newaxis,:]-P[np.newaxis,:,:]
D=np.sqrt(np.sum(diff**2,axis=2))
print(D)
i,j=np.unravel_index(np.argmax(D),D.shape)
print("maximum distance:",D[i][j])
print("Points pair:",i+1,"and",j+1)
print("point:",P[i],"and",P[j])
